### ISSUE TITLE
Bug: Node Modules directory committed to repo

### ISSUE THREAD

**Issue by MattGibney** [jwpf100/node-blog#9]
### Problem
`node_modules` directory is committed to repository. There are two issues with this:
1. Having so many tracked files makes pulling the repository take a lot longer than it needs to (This is especially a problem if you ever get into automated deployment where you pay for server time).
2. The directory has been added to the `.gitignore` file so further changes aren't being tracked anyway.

### Acceptance Criteria
* `node_modules` directory is removed from version control.

**Comment by jwpf100** [comment]
@MattGibney Hey Matt, I couldn't add you as a reviewer to the pull request above, but I think this should make it visible to you.

**Comment by MattGibney** [comment]
You couldn't as me as a reviewer as the PR was marked as a draft. I updated it to remove the Draft status and added myself as a reviewer.
